set_property SRC_FILE_INFO {cfile:D:/sysI/sys1-sp25/repo/sys-project/lab0-2/syn/nexysa7.xdc rfile:D:/sysI/sys1-sp25/repo/sys-project/lab0-2/syn/nexysa7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN {J15} [get_ports {SW0}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN {L16} [get_ports {SW1}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN {M13} [get_ports {SW2}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN {H17} [get_ports {LD0}]
